# Generated by Django 4.2.7 on 2023-12-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_task_options_remove_task_kolvo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Часы', 'verbose_name_plural': 'Часы'},
        ),
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='task',
            name='place',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='task',
            name='square',
            field=models.CharField(max_length=100, verbose_name='Адрес заказа'),
        ),
    ]
